name: Build Docker Image

on:
  push:
    paths:
      - build.sh
      - .github/workflows/build.yml
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: amd64
          - arch: arm64
    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Install Chisel
        uses: shyim/chisel-installer@main

      - name: Login into Github Docker Registery
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: ./build.sh ${{ matrix.arch }} --push
  merge:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Login into Github Docker Registery
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - run: docker manifest create ghcr.io/friendsofshopware/code-style:latest --amend ghcr.io/friendsofshopware/code-style-amd64 --amend ghcr.io/friendsofshopware/code-style-arm64

      - run: docker manifest push ghcr.io/friendsofshopware/code-style:latest